/* GENERATED by web/scripts/build-evidence.mjs — do not edit. Every value is read from
 * the artefact named in the script; the page types none of them. Regenerate with
 * `pnpm evidence` after any artefact changes and commit the result. */
export const E = {
  "window": {
    "from": "2026-08-27",
    "to": "2026-09-07"
  },
  "study": {
    "cells": "16",
    "paths": "800",
    "arms": "5",
    "ledgers": "8,000",
    "pooledBps": "155.4",
    "materialBps": "200.1",
    "materialPct": "76.4",
    "vsAttentiveBps": "0.0",
    "vsAttentiveTies": "353",
    "vsPassiveBps": "164.6",
    "nightLossPp": "23.5",
    "leadThreeBooksPp": "+13.6",
    "leadOneBookPp": "+3.0",
    "ciLevelPct": "95",
    "contrastsSpanningZero": "9",
    "contrasts": "55",
    "clockContrastsSpanningZero": "3",
    "agentEquityPct": "−47.4",
    "passiveEquityPct": "−49.4",
    "wickLossPct": "11.0",
    "wickPaths": "200",
    "c1bInflation": "4.3"
  },
  "guard": {
    "identity": "2009",
    "contract": "0x47F7471909BD3276D83B743696cdf0bE73811C06",
    "repaySeconds": "6",
    "hfBefore": "0.9600",
    "hfAfter": "1.2362",
    "debtRepaid": "371.49",
    "repayCount": "11",
    "dipPct": "35",
    "hfDip0": "1.6464",
    "hfDip1": "1.0702",
    "hfHuman1": "1.3996",
    "collateral": "2,494.55",
    "debt": "1,212.09",
    "penaltyLo": "60.60",
    "penaltyHi": "121.21",
    "hatchHideS": "30",
    "hatchOfferS": "45",
    "bonusLo": "5",
    "bonusHi": "10",
    "repayTx": "0xbe97e2fabc97498a35fc0b674552e0eb225af14c08c37e0875430dc5d915c7d8",
    "protectTx": "0xda75aae584a3d10b66f8aebc3ef280e3f09c7f5f49840ad2c14c09a6a5c76658",
    "dipTx": "0xadd77a012ad9c05b178d86d1be8e3fb75da8a8ca35c32734598fb48cc147c496",
    "humanSeconds": "55",
    "humanAfterHatchSeconds": "10"
  },
  "ranger": {
    "days": "9.0821",
    "daysShort": "9.08",
    "inRangePct": "100.00",
    "inRangeSeconds": "784,510",
    "holdingSeconds": "784,510",
    "rangeExits": "0",
    "positions": "6",
    "cycleWins": "0",
    "cycles": "5",
    "gasMultiple": "1.35",
    "netPct": "−4.61",
    "netAgentUsd": "39.845",
    "netHoldUsd": "41.772",
    "incomeUsd": "0.272",
    "gasUsd": "0.368",
    "transactions": "48",
    "nonceLo": "0",
    "nonceHi": "47",
    "failed": "0",
    "drawdownPct": "3.15",
    "bnbDrawdownPct": "4.99",
    "basketDrawdownPct": "3.27",
    "grossYieldPct": "0.6886",
    "breakevenUsd": "53",
    "entryUsd": "39.96",
    "entryBnbSharePct": "65",
    "peakAtRiskUsd": "40.54",
    "observabilityGapDays": "5.68"
  },
  "hires": {
    "jobs": "6",
    "delivered": "4",
    "agents": "5",
    "operators": "3",
    "categories": "4",
    "deliveryLo": "21",
    "deliveryHi": "39",
    "priceU": "0.001",
    "escrowPaidU": "0.015",
    "escrowStrandedU": "0.011",
    "stalenessLo": "7.0",
    "stalenessHi": "57.1",
    "relicPriceU": "0.01",
    "relicWait": "3 h 40 min",
    "insideTicks": "605"
  },
  "humanBaseline": {
    "date": "2026-09-08",
    "method": "stopwatch",
    "fastest": "2:25",
    "slowest": "13:32",
    "fastestMinutes": "2",
    "slowestMinutes": "14"
  },
  "links": {
    "report": {
      "words": "5,570",
      "minutes": "23"
    },
    "rangeRecord": {
      "words": "11,004",
      "minutes": "46"
    },
    "hires": {
      "words": "2,387",
      "minutes": "10"
    },
    "advantage": {
      "words": "2,155",
      "minutes": "9"
    },
    "study": {
      "words": "27,247",
      "minutes": "114"
    },
    "brief": {
      "words": "614",
      "minutes": "3"
    }
  }
} as const;

/** Figure B1 geometry: book-level survival at 01:00 minus 09:30, per arm, with 95% cluster-bootstrap intervals. */
export const B1 = {
  "width": 720,
  "labelGutter": 190,
  "right": 64,
  "rowHeight": 44,
  "top": 12,
  "axis": 30,
  "height": 262,
  "zeroX": 539.5,
  "ticks": [
    {
      "v": -30,
      "x": 190,
      "label": "−30"
    },
    {
      "v": -20,
      "x": 306.5,
      "label": "−20"
    },
    {
      "v": -10,
      "x": 423,
      "label": "−10"
    },
    {
      "v": 0,
      "x": 539.5,
      "label": "0"
    },
    {
      "v": 10,
      "x": 656,
      "label": "+10"
    }
  ],
  "rows": [
    {
      "arm": "A",
      "label": "the agent",
      "tone": "chart-1",
      "modelled": false,
      "point": 1.374999999999993,
      "lo": -3.3699741643300904,
      "hi": 6.068479805058754,
      "coversZero": true,
      "y": 34,
      "x0": 500.23980098555444,
      "x1": 610.1977897289346,
      "xp": 555.51875,
      "valueLabel": "+1.4",
      "ciLabel": "[−3.4, +6.1]"
    },
    {
      "arm": "H1",
      "label": "attentive person",
      "tone": "chart-2",
      "modelled": true,
      "point": 1.2499999999999956,
      "lo": -4.718539129361424,
      "hi": 7.327175245179463,
      "coversZero": true,
      "y": 78,
      "x0": 484.5290191429394,
      "x1": 624.8615916063407,
      "xp": 554.0625,
      "valueLabel": "+1.2",
      "ciLabel": "[−4.7, +7.3]"
    },
    {
      "arm": "H2",
      "label": "person on a schedule",
      "tone": "chart-2",
      "modelled": true,
      "point": -23.5,
      "lo": -28.261624108712436,
      "hi": -18.838423679578092,
      "coversZero": false,
      "y": 122,
      "x0": 210.25207913350013,
      "x1": 320.03236413291523,
      "xp": 265.725,
      "valueLabel": "−23.5",
      "ciLabel": "[−28.3, −18.8]"
    },
    {
      "arm": "H3",
      "label": "person who sleeps",
      "tone": "chart-2",
      "modelled": true,
      "point": -22.874999999999996,
      "lo": -27.92804049981738,
      "hi": -17.91014204527219,
      "coversZero": false,
      "y": 166,
      "x0": 214.1383281771275,
      "x1": 330.84684517257904,
      "xp": 273.00625,
      "valueLabel": "−22.9",
      "ciLabel": "[−27.9, −17.9]"
    },
    {
      "arm": "P",
      "label": "doing nothing",
      "tone": "chart-3",
      "modelled": false,
      "point": 0,
      "lo": -1.7493054029413395,
      "hi": 1.7772859161592973,
      "coversZero": true,
      "y": 210,
      "x0": 519.1205920557334,
      "x1": 560.2053809232558,
      "xp": 539.5,
      "valueLabel": "0.0",
      "ciLabel": "[−1.7, +1.8]"
    }
  ]
} as const;

/** The six hires, one row per job, from E4 block timestamps and the E1 staleness table. */
export const HIRES = [
  {
    "job": 1032,
    "agentId": 2003,
    "agent": "Canned Health Guard",
    "category": "health factor",
    "priceU": 0.001,
    "delivered": false,
    "deliverySeconds": null,
    "stalenessDays": null,
    "fundedAtUtc": "2026-09-06T07:02:03Z",
    "submittedAtUtc": null,
    "outcome": "FUNDED, never submitted"
  },
  {
    "job": 1033,
    "agentId": 2003,
    "agent": "Canned Health Guard",
    "category": "health factor",
    "priceU": 0.001,
    "delivered": true,
    "deliverySeconds": 23,
    "stalenessDays": 9.8,
    "fundedAtUtc": "2026-09-06T07:12:15Z",
    "submittedAtUtc": "2026-09-06T07:12:38Z",
    "outcome": "SUBMITTED and SETTLED"
  },
  {
    "job": 1034,
    "agentId": 2005,
    "agent": "Canned Range Keeper",
    "category": "rebalancing",
    "priceU": 0.001,
    "delivered": true,
    "deliverySeconds": 39,
    "stalenessDays": 57.1,
    "fundedAtUtc": "2026-09-06T07:14:16Z",
    "submittedAtUtc": "2026-09-06T07:14:55Z",
    "outcome": "SUBMITTED and SETTLED"
  },
  {
    "job": 1035,
    "agentId": 2034,
    "agent": "Canned Yield Scout",
    "category": "yield optimisation",
    "priceU": 0.001,
    "delivered": true,
    "deliverySeconds": 37,
    "stalenessDays": 56.7,
    "fundedAtUtc": "2026-09-06T07:15:21Z",
    "submittedAtUtc": "2026-09-06T07:15:58Z",
    "outcome": "SUBMITTED and SETTLED"
  },
  {
    "job": 1037,
    "agentId": 2045,
    "agent": "Canned Grid Keeper",
    "category": "grid trading",
    "priceU": 0.001,
    "delivered": true,
    "deliverySeconds": 21,
    "stalenessDays": 7,
    "fundedAtUtc": "2026-09-06T07:16:24Z",
    "submittedAtUtc": "2026-09-06T07:16:45Z",
    "outcome": "SUBMITTED and SETTLED"
  },
  {
    "job": 1038,
    "agentId": 1840,
    "agent": "Relic Health Factor Monitor",
    "category": "health factor",
    "priceU": 0.01,
    "delivered": false,
    "deliverySeconds": null,
    "stalenessDays": null,
    "fundedAtUtc": "2026-09-06T07:17:21Z",
    "submittedAtUtc": null,
    "outcome": "FUNDED, never submitted"
  }
] as const;

/** The five completed rebalance cycles, from E2 winRate C1 (the number that must not be dressed up). */
export const CYCLES = [
  {
    "cycle": 1,
    "tokenId": "7268711",
    "mintIso": "2026-08-28T07:34:41.000Z",
    "closeIso": "2026-08-28T18:39:07.000Z",
    "heldSeconds": 39866,
    "entryNotionalUsd": 39.958556,
    "bnbMovePercent": -3.4555,
    "impermanentLossUsd": -0.126924,
    "swapFeesUsd": 0.017567,
    "cakeUsd": 0.002436,
    "gasUsd": 0.063557,
    "netVsHoldingUsd": -0.170478,
    "beatHolding": false
  },
  {
    "cycle": 2,
    "tokenId": "7272152",
    "mintIso": "2026-08-28T18:39:19.000Z",
    "closeIso": "2026-09-03T10:56:32.000Z",
    "heldSeconds": 490633,
    "entryNotionalUsd": 38.958173,
    "bnbMovePercent": 2.8031,
    "impermanentLossUsd": -0.081373,
    "swapFeesUsd": 0.095367,
    "cakeUsd": 0.039786,
    "gasUsd": 0.05884,
    "netVsHoldingUsd": -0.00506,
    "beatHolding": false
  },
  {
    "cycle": 3,
    "tokenId": "7316556",
    "mintIso": "2026-09-03T10:56:40.000Z",
    "closeIso": "2026-09-03T16:00:17.000Z",
    "heldSeconds": 18217,
    "entryNotionalUsd": 39.293144,
    "bnbMovePercent": 3.1883,
    "impermanentLossUsd": -0.10063,
    "swapFeesUsd": 0.01446,
    "cakeUsd": 0.00271,
    "gasUsd": 0.058491,
    "netVsHoldingUsd": -0.141952,
    "beatHolding": false
  },
  {
    "cycle": 4,
    "tokenId": "7319374",
    "mintIso": "2026-09-03T16:02:41.000Z",
    "closeIso": "2026-09-05T08:24:52.000Z",
    "heldSeconds": 145331,
    "entryNotionalUsd": 39.605351,
    "bnbMovePercent": 3.0683,
    "impermanentLossUsd": -0.09716,
    "swapFeesUsd": 0.055877,
    "cakeUsd": 0.012331,
    "gasUsd": 0.076047,
    "netVsHoldingUsd": -0.104999,
    "beatHolding": false
  },
  {
    "cycle": 5,
    "tokenId": "7336818",
    "mintIso": "2026-09-05T08:25:01.000Z",
    "closeIso": "2026-09-05T14:55:31.000Z",
    "heldSeconds": 23430,
    "entryNotionalUsd": 40.003445,
    "bnbMovePercent": 2.8071,
    "impermanentLossUsd": -0.085796,
    "swapFeesUsd": 0.028454,
    "cakeUsd": 0.002956,
    "gasUsd": 0.067806,
    "netVsHoldingUsd": -0.122192,
    "beatHolding": false
  }
] as const;

/** The six positions, from E2 winRate A (time in range). */
export const POSITIONS = [
  {
    "tokenId": "7268711",
    "mintBlock": 118536451,
    "closeBlock": 118625020,
    "heldSeconds": 39866,
    "inRangeFraction": 1,
    "rangeExits": 0,
    "smallestHeadroomTicks": 313
  },
  {
    "tokenId": "7272152",
    "mintBlock": 118625047,
    "closeBlock": 119714487,
    "heldSeconds": 490633,
    "inRangeFraction": 1,
    "rangeExits": 0,
    "smallestHeadroomTicks": 367
  },
  {
    "tokenId": "7316556",
    "mintBlock": 119714506,
    "closeBlock": 119754973,
    "heldSeconds": 18217,
    "inRangeFraction": 1,
    "rangeExits": 0,
    "smallestHeadroomTicks": 336
  },
  {
    "tokenId": "7319374",
    "mintBlock": 119755292,
    "closeBlock": 120078128,
    "heldSeconds": 145331,
    "inRangeFraction": 1,
    "rangeExits": 0,
    "smallestHeadroomTicks": 348
  },
  {
    "tokenId": "7336818",
    "mintBlock": 120078147,
    "closeBlock": 120130205,
    "heldSeconds": 23430,
    "inRangeFraction": 1,
    "rangeExits": 0,
    "smallestHeadroomTicks": 368
  },
  {
    "tokenId": "7340903",
    "mintBlock": 120130230,
    "closeBlock": null,
    "heldSeconds": 67033,
    "inRangeFraction": 1,
    "rangeExits": 0,
    "smallestHeadroomTicks": 510
  }
] as const;

/** The nine-day economics, numeric, from E2 gasVersusIncome / yields / netVersusHolding. */
export const ECON = {
  "windowDays": 9.0821,
  "windowStartIso": "2026-08-28T07:34:41.000Z",
  "windowEndIso": "2026-09-06T09:32:56.000Z",
  "startBlock": 118536451,
  "endBlock": 120279139,
  "transactions": 48,
  "incomeUsd": 0.271942,
  "swapFeesUsd": 0.211725,
  "cakeUsd": 0.060218,
  "gasUsd": 0.368063,
  "grossYieldPct": 0.6886,
  "twaNotionalUsd": 39.490415,
  "breakevenUsd": 53.45,
  "entryUsd": 39.958556,
  "agentNetUsd": 39.845391,
  "holdEntryBasketUsd": 41.771576,
  "netVsHoldPct": -4.6112,
  "observabilityGapFromIso": "2026-08-28T18:39:13.000Z",
  "observabilityGapToIso": "2026-09-03T10:56:32.000Z"
} as const;

/** The four scored hires, both ways: agent arm (A) against the no-agent script (C), from T*-score.json. */
export const TASKS = [
  {
    "id": "T1",
    "title": "Health factor and smallest sufficient repay for one Venus Core Pool account",
    "category": "health factor monitoring",
    "highStakes": "security",
    "job": 1033,
    "agentId": 2003,
    "agent": "Canned Health Guard",
    "agentSeconds": 23,
    "agentPriceU": 0.001,
    "agentPoints": 2,
    "outOf": 10,
    "agentStalenessDays": 9.8,
    "scriptSeconds": 1.3,
    "scriptRuns": 2,
    "scriptCalls": 3,
    "scriptPoints": 10,
    "humanRun": true,
    "humanElapsed": "6:10",
    "humanSeconds": 370,
    "humanCostU": 0,
    "humanMethod": "stopwatch",
    "files": {
      "score": "T1-score.json",
      "hire": "hire-97-2003-job-1033.json"
    }
  },
  {
    "id": "T3",
    "title": "Where 1000 USDT should sit on BNB Chain right now, and by how much",
    "category": "yield optimisation",
    "highStakes": null,
    "job": 1035,
    "agentId": 2034,
    "agent": "Canned Yield Scout",
    "agentSeconds": 37,
    "agentPriceU": 0.001,
    "agentPoints": 8,
    "outOf": 10,
    "agentStalenessDays": 56.7,
    "scriptSeconds": 6.2,
    "scriptRuns": 2,
    "scriptCalls": 23,
    "scriptPoints": 10,
    "humanRun": true,
    "humanElapsed": "13:32",
    "humanSeconds": 812,
    "humanCostU": 0,
    "humanMethod": "stopwatch",
    "files": {
      "score": "T3-score.json",
      "hire": "hire-97-2034-job-1035.json"
    }
  },
  {
    "id": "T4",
    "title": "Realised volatility and a grid specification for PancakeSwap V3 WBNB/USDT 0.05%",
    "category": "grid trading",
    "highStakes": "trading",
    "job": 1037,
    "agentId": 2045,
    "agent": "Canned Grid Keeper",
    "agentSeconds": 21,
    "agentPriceU": 0.001,
    "agentPoints": 5,
    "outOf": 10,
    "agentStalenessDays": 7,
    "scriptSeconds": 2.6,
    "scriptRuns": 2,
    "scriptCalls": 11,
    "scriptPoints": 10,
    "humanRun": true,
    "humanElapsed": "10:42",
    "humanSeconds": 642,
    "humanCostU": 0,
    "humanMethod": "stopwatch",
    "files": {
      "score": "T4-score.json",
      "hire": "hire-97-2045-job-1037.json"
    }
  },
  {
    "id": "T6",
    "title": "Is a PancakeSwap V3 WBNB/USDT position in range, and where would you re-range it",
    "category": "rebalancing",
    "highStakes": "trading",
    "job": 1034,
    "agentId": 2005,
    "agent": "Canned Range Keeper",
    "agentSeconds": 39,
    "agentPriceU": 0.001,
    "agentPoints": 6,
    "outOf": 10,
    "agentStalenessDays": 57.1,
    "scriptSeconds": 1.9,
    "scriptRuns": 3,
    "scriptCalls": 8,
    "scriptPoints": 10,
    "humanRun": true,
    "humanElapsed": "2:25",
    "humanSeconds": 145,
    "humanCostU": 0,
    "humanMethod": "stopwatch",
    "files": {
      "score": "T6-score.json",
      "hire": "hire-97-2005-job-1034.json"
    }
  }
] as const;
